-- Add a second join reminder type for 10 minutes before start
-- Extend reminders_sent.type check constraint to allow 'join10'

do $$
begin
  -- Drop existing type check constraint if it exists (typical autogenerated name)
  if exists (
    select 1 from pg_constraint
     where conname = 'reminders_sent_type_check'
  ) then
    alter table reminders_sent drop constraint reminders_sent_type_check;
  end if;
exception when others then
  -- ignore; we'll attempt to add the new constraint below
  null;
end $$;

alter table reminders_sent
  add constraint reminders_sent_type_check
  check (type in ('vote','join','join10'));

